### PR TITLE
Update Configuration for recent Gluon versions

### PR DESCRIPTION
**Pull request by kenohassler**
This patch set solves two build problems I encountered when building Gluon v2023.2.3 with the FreifunkSaar configuration:
* `GLUON_FEATURES` and `GLUON_SITE_PACKAGES` are deprecated and have been replaced by image-customization.lua. The patch creates this file and uses the same options that were in site.mk before. See https://gluon.readthedocs.io/en/latest/releases/v2023.2.html#image-customization
* The key mesh_vpn.tunneldigger.mtu needs to be set explicitly. I followed the recommendation from https://gluon.readthedocs.io/en/latest/user/mtu.html and set it to 1312 for all seven domains.

Note, the version number should probably be bumped as well. I have successfully built and tested the ipq40xx-generic target.

_I emailed this patch to the hacksaar gitlab, but it never showed up as a merge request. I suspect the configuration might be broken, hence the duplicate here._

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks for the PR!

Unfortunately we currently don't really have anyone who's taking care of firmware updates. If you want to help with Freifunk Saar firmware, any chance you could come to the hackerspace one Wednesday and get in touch with the Freifunk folks there? :)  I don't live in Saarbrücken any more, but maybe you can coordinate with some of the people that do still live there to make sure they will be around.

> I emailed this patch to the hacksaar gitlab, but it never showed up as a merge request. I suspect the configuration might be broken, hence the duplicate here.

Sending an email won't make a merge request, so I am confused about this comment.

This repo here is old and dead, but gitlab works like github so you should be able to fork https://git.hacksaar.de/FreifunkSaar/gluon-site and then make an MR there.

**Comment by kenohassler** [comment]
Hi Ralf!

> Sending an email won't make a merge request, so I am confused about this comment.
>
> This repo here is old and dead, but gitlab works like github so you should be able to fork https://git.hacksaar.de/FreifunkSaar/gluon-site and then make an MR there.

That was indeed my intention! However, I'm not permitted to fork the GitLab repo, and when I tried to create a merge request, I was presented with this:
mr-crop
I hadn't seen this before, but I did as instructed and sent an email to the indicated address -- but apparently it landed in the limbus :)

Sure, I'd like to help. I'll drop a message on Matrix.

**Comment by RalfJung** [comment]
Wow I have never seen that gitlab feature before. No idea what happens when you send an email there without even having a fork -- I don't see how that could possibly make sense. It certainly did not create a [merge request](https://git.hacksaar.de/FreifunkSaar/gluon-site/-/merge_requests), nor send an email to the people subscribed to that repo...

If you let me know your git.hacksaar.de username, I can unlock forks for your account. We had to lock this all down because of spam, though with the extra password required for login maybe we can allow forks more easily now... I'll leave that to the current admins to decide.

**Comment by kenohassler** [comment]
Sure, this is me: https://git.hacksaar.de/kenohassler

**Comment by RalfJung** [comment]
Okay, you should now be able to create forks. :)

**Comment by kenohassler** [comment]
Perfect! I created an MR on GitLab and will close this one.

**Pull request closed without merging**
